#ifndef CROSSPROJECTMANAGER_GLOBAL_H
#define CROSSPROJECTMANAGER_GLOBAL_H

#include <QtGlobal>

#if defined(CROSSPROJECTMANAGER_LIBRARY)
#  define CROSSPROJECTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CROSSPROJECTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CROSSPROJECTMANAGER_GLOBAL_H

