include($$QTCREATOR_SOURCES/src/plugins/projectexplorer/projectexplorer.pri)
include($$QTCREATOR_SOURCES/src/plugins/qtsupport/qtsupport.pri)
include($$QTCREATOR_SOURCES/src/plugins/remotelinux/remotelinux.pri)
include($$QTCREATOR_SOURCES/src/plugins/debugger/debugger.pri)
include($$QTCREATOR_SOURCES/src/plugins/qt4projectmanager/qt4projectmanager.pri)
include($$QTCREATOR_SOURCES/src/libs/ssh/ssh.pri)
